### ISSUE TITLE
Double job?

### ISSUE THREAD

**Issue by Starec666** [beanjo55/ccminer-nanashi#1]
Hello!
I've noticed some case, when I mine solo, and ar 40sec there is no any solved block, my node send same block again, and treads with nonces are reseting.
So, Are all the treads do the same job after reset with the same block?
Or hash changes because of the time field?  

![doublejob](https://user-images.githubusercontent.com/36118638/36810499-ecd1fe6a-1cdb-11e8-823a-794e295108e6.jpg)

**Comment by beanjo55** [comment]
This is not an issue. 
The current block notice has two triggers, a new block and a timer. 
It updates in a new block but if there is no new block after a certain amount of time it displays it again

**Comment by Starec666** [comment]
could you make me build with 
				(!allow_gbt && work_decode(json_object_get(val, "result"), &g_work))) {
				//restart_threads();

at 3110 line?

**Comment by beanjo55** [comment]
Unfortunately, this has no effect. 
That line falls under one of the longpoll methods, and to solo mine one of the arguments is 
—no-longpoll meaning that line is never run

**Comment by Starec666** [comment]
I've just checked, I didn't use —no-longpoll in my solo, and it works, I mined for a week already.
Does it changed something for me?
I see without this option packet with new block receives faster, like ping less for 1-3 sec, 
But with option —no-longpoll I receive information that block is the same for every 10 seconds
and without —no-longpoll I received block information every 40 second
So threads reset 1 case is every 10seconds
2 case - reset threads every 40 seconds

**Comment by beanjo55** [comment]
The miner is not intended to be used without —no-longpoll so that could explain the strange behavior. Interesting observations though, but it also appears that the behavior is intentional and can co firm that the miner does find blocks when using the appropriate settings.

**Comment by Starec666** [comment]
Hello again!
could you make me build with
**restart_threads();**  replace to **If (g_work.height != work.height) {restart_threads();}**

at 3110 line?
I've stayed running ccminer with —no-longpoll, but that idea about restart threads doesn't make me calm.
I've tried to build it myself, installed VS, but it needs CUDA 9.1 toolkit, and I think it's not the last obstruction on my way.
Please help me with this idea?

**Comment by beanjo55** [comment]
No sorry, not making builds at request. 

There is no issue with how it behaves, working as intended.

**Comment by Starec666** [comment]
It's not an issue ofcourse, I checked that curdate updates every time, so hash is different, I just trying to find better hash variety)

**Comment by Starec666** [comment]
Hello beanjo55!
I've tried to mine lyra2z coin, it has 5 minutes block interval
So I have such a problem:
when I mine with option  --no-longpoll, miner restarts threads every 10second, as default in _-s_ option, ok, I put 300s as block perios is, but with _-s 300_ miner is searching hash for 300s, even if block was found already it is still doing same job. Miner is doing stale job in this case.

Ok, I mine without this option - then miner get job very fast, just in moment as new block found, but every 60s it resets threads.

I've take a look code
uint32_t scan_time = have_longpoll ? LP_SCANTIME : opt_scantime;

LP_SCANTIME is 60s, so when I play without longpool - it resets job every 60, But I dont need this reset, because miner will get new job by himself online.
If It is nessesary option, please could you do it setable by params in options, maybe it should be same -s, --scantime=N      upper bound on time spent scanning current work when\n\?

And what I'm doing wrong with option --no-longpoll? why miner is doing stale job and reset jobs every -s parameter?

**Comment by Starec666** [comment]
whole day I'm trying to compile the build with vs2015, and every time there is a new mistake in log or something is missing(

**Comment by beanjo55** [comment]
hey, I can look into this. could you link me to it?

As for the LP_SCANTIME, its only used in the longpoll method, so it has no effect when --no-longpoll is used. 
I can'd say for sure if --no-longpoll is needed for other coins, as I have not tested any coin other than ravencoin and garlicoin, but am working to support all coins that the miner can mine.
I am busy for a while, but will look at this next time I have a chance to, hopefully for the next release.

Compiling is a bit tricky, I used Visual Studio 17 with no updates,  VC++ compiler v141, Windows SDK 10.0.16299.0, Cuda 9.1 with update 1, and the windows version is Fall creators update.
I have not been able to recreate the development environment on a second machine yet, but that is the config on the one I have working, if it helps

**Comment by Starec666** [comment]
I use the same sonfig, except vs2015, and I can't to defeat errors, bignum.hpp alot of errors.

Please, could you just make me build with
	before:  uint32_t scan_time = have_longpoll ? LP_SCANTIME : opt_scantime;
	after:     uint32_t scan_time = opt_scantime;

line 2200 in ccminer.cpp.

Nobody uses longpoll except me I guess, but I need it, it makes me faster in block finding
I'm not a lazy, I realy spent a day do make my own build, and now I give up, feels very upset. 
I used to programming at University, but it's not my profession right now.

**Comment by beanjo55** [comment]
I am looking into it, it looks like longpoll should work as long as the coin implemented it correctly and I did not accidentally break it(which may have happened somewhere along the way), what coin are you trying to mine?

**Comment by Starec666** [comment]
I'm still mining Garlic, but tried to mine Taler Lyra2z, and it started to mine well, but Taler has 5 minutes block period, and miner resets threads every 60sec, I think its because of LP_SCANTIME.

Sometimes in Garlic nobody found block for >1min, but ccminer resets threads, ans start from begining every 60s.

**Comment by beanjo55** [comment]
ok thanks, ill take a look and do some testing, will try to have an answer, fix, or workaround by next week.

if you have anything else to add, add it to #4
