### ISSUE TITLE
possible longpoll issues

### ISSUE THREAD

**Issue by beanjo55** [beanjo55/ccminer-nanashi#4]
timing issues, miner works on old block or resets progress before next block

**Comment by Starec666** [comment]
Hi!
Also I have some idea. I called it - rotation nounce.
What if not to reset  nonce every new block.
Everyone knows that sometimes we have luck period and unluck.
So when we have luck period, better is to use same or near same values of nonce as previous lucky block, so next block is better to continue with same nonce as previous. Not to start from standart begining.
Example:
[2018-03-22 23:27:21] Current block is 130101
[2018-03-22 23:27:21] job  target change: 19e9700 (0.0)
[2018-03-22 23:27:21] GPU #4: start=**7ffffffe** end=99c1109a range=19c1109c
[2018-03-22 23:27:22] job  target change: 19e9700 (0.0)
[2018-03-22 23:27:22] GPU #5: start=**bffffffd** end=d90dd61a range=190dd61d
[2018-03-22 23:27:22] job  target change: 19e9700 (0.0)
[2018-03-22 23:27:22] GPU #2: start=**00000000** end=19a78ee2 range=19a78ee2
[2018-03-22 23:27:22] job  target change: 19e9700 (0.0)
[2018-03-22 23:27:22] GPU #3: start=**3fffffff** end=593aaa88 range=193aaa89

Every time it starts from this numbers, its so usual that I even hate this numbers)

Also small hash rigs will all time start from 00000000 and solve 1000-2000 nonce, again and again, but who knows maybe its luck is after 10000000 or 30000000.

So reset nonce only when we get to ffffffff.

**Comment by beanjo55** [comment]
unfortunately, this does not work because you assume valid nonces will be close

this is incorrect, as even a single bit change in the nonce can drastically change the output hash.

**Comment by Starec666** [comment]
beanjo55 please release any update for this case, I'm waiting it so much!

**Comment by beanjo55** [comment]
after looking into it, nothing appears to be wrong with it, is working as intended

**Comment by Starec666** [comment]
Oh man, but why it resets progress every 60s in longpoll mode? It's not a right way.
f8ck I waited 2 weeks for any updates. No success.

**Comment by Starec666** [comment]
make me a build with it, I cant do it myself, I tried, and no success, hate this VS2015

**Comment by beanjo55** [comment]
look, I am not making custom builds for people for an issue that does not exist, especially when they demand with the words "make me a build" 

There is no issue, it works for everyone but you,  if it bothers you, use --no-longpoll like everyone else

**Comment by Starec666** [comment]
noone think about how it should works, ebery one just run the button, so if nobody tell you that there is an issue, it doenst mean there is no issue. I gave you detailed facts that there is a problem. And you just sad it ok.

**Comment by beanjo55** [comment]
whatever issue you have, I can not recreate. so either stick to --no-longpoll, which works, or live with whatever behavior you have.

**Comment by Starec666** [comment]
yes, it works like a shit )

**Comment by beanjo55** [comment]
being a dick isn't helping. I have done everything that I can to investigate the behavior and found no issues with the miner

**Comment by beanjo55** [comment]
If you can write a fix and prove that it fixes the issue, I am more than happy to add that fix, but i am not going to spend my time trying to fix ghost issues

**Comment by Starec666** [comment]
I'm not able to check my fixes because I'm not able to make my own build.

**Comment by beanjo55** [comment]
not my problem
