### ISSUE TITLE
compilation of 2.3.1 on Ubuntu 16.04.1 fails

### ISSUE THREAD

**Issue by holitics** [beanjo55/ccminer-nanashi#6]
I pulled code down from the "Releases" section, the filename was: ccminer-nanashi-2.3.1.tar.gz. The same exact thing happens if I git clone directly.

Running autogen, configure, build all worked great until:

.....
ccminer-ccminer.o: In function `miner_thread(void*)':
ccminer.cpp:(.text+0x8ae5): undefined reference to `scanhash_x16r'
ccminer-util.o: In function `print_hash_tests':
util.cpp:(.text+0x7d79): undefined reference to `x16r_hash'
ccminer-bench.o: In function `algo_free_all':
bench.cpp:(.text+0x222): undefined reference to `free_x16r'
x15/cuda_x15_whirlpool_sm3.o: In function `x16_whirlpool512_setBlock_80(void*)':
tmpxft_000056ec_00000000-5_cuda_x15_whirlpool_sm3.compute_50.cudafe1.cpp:(.text+0xbc8): undefined reference to `whirlpool_midstate(void*, void const*)'
collect2: error: ld returned 1 exit status
Makefile:1184: recipe for target 'ccminer' failed
make[2]: *** [ccminer] Error 1
make[2]: Leaving directory '/home/nick/ccminer.2.3.2.nanashi.solo/ccminer-nanashi-2.3.1'
Makefile:2201: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/nick/ccminer.2.3.2.nanashi.solo/ccminer-nanashi-2.3.1'
Makefile:654: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by beanjo55** [comment]
Yea, I mainly build and use windows, so the makefile has not been updated. I have been procrastination on getting a linux VM set up, so I will get to htat withing the next two days or so

**Comment by holitics** [comment]
OK, I updated the Makefile and it now compiles and works fine.

**Comment by beanjo55** [comment]
should be fixed in latest commits on both dev and master
